"""Generate the public-to-the-private-repo mission progress snapshot."""

from __future__ import annotations

import csv
import hashlib
import re
import subprocess
from datetime import datetime, timedelta, timezone
from decimal import Decimal
from pathlib import Path


MISSION_TZ = timezone(timedelta(hours=1), name="BST")
DEADLINE = datetime(2026, 9, 17, 19, 9, tzinfo=MISSION_TZ)
TEXT_SUFFIXES = {".csv", ".json", ".md", ".mjs", ".py", ".txt"}
TEXT_FILENAMES = {".gitattributes", ".gitignore"}


def _tracked_files(root: Path) -> list[Path]:
    result = subprocess.run(
        ["git", "ls-files", "-z"],
        cwd=root,
        check=True,
        capture_output=True,
    )
    files = []
    for raw in result.stdout.decode("utf-8").split("\0"):
        if raw and raw != "progress.txt":
            path = root / raw
            if path.is_file():
                files.append(path)
    return sorted(files, key=lambda item: item.relative_to(root).as_posix())


def compute_repo_fingerprint(root: Path) -> str:
    digest = hashlib.sha256()
    for path in _tracked_files(root):
        relative_text = path.relative_to(root).as_posix()
        relative = relative_text.encode("utf-8")
        digest.update(len(relative).to_bytes(4, "big"))
        digest.update(relative)
        content = path.read_bytes()
        if (
            path.suffix.lower() in TEXT_SUFFIXES
            or path.name in TEXT_FILENAMES
            or relative_text.startswith(".githooks/")
        ):
            content = content.replace(b"\r\n", b"\n").replace(b"\r", b"\n")
        digest.update(len(content).to_bytes(8, "big"))
        digest.update(content)
    return digest.hexdigest()


def _read_csv(path: Path) -> list[dict[str, str]]:
    with path.open(encoding="utf-8-sig", newline="") as handle:
        return list(csv.DictReader(handle))


def _line_value(text: str, label: str) -> str:
    match = re.search(rf"^- {re.escape(label)}:\s*(.+)$", text, re.MULTILINE)
    if not match:
        raise ValueError(f"Missing line {label!r}")
    return match.group(1).strip()


def _emphasis_value(text: str, label: str) -> str:
    match = re.search(rf"^\*\*{re.escape(label)}:\*\*\s*(.+)$", text, re.MULTILINE)
    if not match:
        raise ValueError(f"Missing emphasized line {label!r}")
    return match.group(1).strip()


def _money_value(text: str, label: str) -> str:
    match = re.search(rf"^- {re.escape(label)}:\s*£([\d,]+(?:\.\d+)?)", text, re.MULTILINE)
    if not match:
        raise ValueError(f"Missing money line {label!r}")
    return f"£{Decimal(match.group(1).replace(',', '')):,.2f}"


def _time_remaining(now: datetime) -> str:
    seconds = max(0, int((DEADLINE - now).total_seconds()))
    days, remainder = divmod(seconds, 86400)
    hours, remainder = divmod(remainder, 3600)
    minutes = remainder // 60
    return f"{days}d {hours}h {minutes}m"


def build_progress(root: Path, now: datetime | None = None) -> str:
    now = now or datetime.now(MISSION_TZ)
    finance = (root / "ops/FINANCE.md").read_text(encoding="utf-8")
    compute = (root / "ops/COMPUTE_BUDGET.md").read_text(encoding="utf-8")
    dashboard = (root / "ops/DASHBOARD.md").read_text(encoding="utf-8")
    state = (root / "ops/STATE.md").read_text(encoding="utf-8")
    mission_log = (root / "ops/MISSION_LOG.md").read_text(encoding="utf-8")
    leads = _read_csv(root / "ops/LEADS.csv")
    contacts = _read_csv(root / "ops/CONTACTS.csv")
    opportunities = _read_csv(root / "ops/OPPORTUNITIES.csv")

    replies = sum(bool(row["reply"].strip()) for row in leads)
    contacted = sum(row["status"] == "contacted" for row in leads)
    qualified = sum(row["status"] in {"contacted", "qualified_hold_secondary"} for row in leads)
    opt_outs = sum(row["opt_out"].strip().lower() == "true" for row in contacts)
    latest_events = [line for line in mission_log.splitlines() if line.startswith("- ")][-8:]

    active_match = re.search(
        r"## Active strategies\s*(.*?)\s*## Funnel",
        dashboard,
        re.DOTALL,
    )
    if not active_match:
        raise ValueError("Dashboard active-strategy block is missing")
    active_strategies = [
        line for line in active_match.group(1).splitlines() if re.match(r"^\d+\. ", line)
    ]

    lines = [
        "SEVEN-DAY REVENUE MISSION - LIVE PROGRESS",
        "",
        "This file is generated by tools/update_progress.py. Do not edit it manually.",
        "Repository: https://github.com/Bleuszz/revenue-os-2026-09-10 (private)",
        f"Generated: {now.strftime('%Y-%m-%d %H:%M:%S %Z')}",
        f"Deadline: {DEADLINE.strftime('%Y-%m-%d %H:%M %Z')}",
        f"Time remaining: {_time_remaining(now)}",
        f"Repository content fingerprint: {compute_repo_fingerprint(root)}",
        "",
        "REALISED FINANCIAL STATE",
        f"Gross cash received: {_money_value(finance, 'Gross cash received')}",
        f"Fees: {_money_value(finance, 'Fees')}",
        f"Expenses: {_money_value(finance, 'Total expenses')}",
        f"Net cash recovery: {_money_value(finance, 'Net cash recovery')}",
        f"Cash remaining from £30 authority: {_money_value(finance, 'Cash remaining')}",
        f"Shortfall to £70 minimum: {_money_value(finance, 'Shortfall to minimum')}",
        "",
        "NON-CASH COMMERCIAL STATE",
        f"Pending payments: {_money_value(finance, 'Pending payments')}",
        f"Signed/agreed work: {_money_value(finance, 'Signed/agreed work')}",
        f"Pipeline: {_line_value(finance, 'Pipeline')}",
        f"Probability-weighted pipeline: {_line_value(finance, 'Probability-weighted pipeline')}",
        f"Uncontacted secondary reserve: {_line_value(finance, 'Uncontacted secondary reserve')}",
        "Only cleared, accessible external-customer cash counts as realised revenue.",
        "",
        "COMPUTE CONTROL",
        f"Weekly Codex usage consumed: {_line_value(compute, 'Codex weekly usage consumed')}",
        f"Weekly Codex usage remaining: {_line_value(compute, 'Codex weekly usage remaining')}",
        f"Allowance reset: {_line_value(compute, 'Allowance reset')}",
        f"Paid usage credits: {_line_value(compute, 'Paid usage credits')}",
        f"Conservation level: {_line_value(compute, 'Compute conservation level')}",
        "",
        "FUNNEL",
        f"Opportunities scored: {len(opportunities)}",
        f"Leads researched: {len(leads)}",
        f"Qualified: {qualified}",
        f"Contacted: {contacted}",
        f"Replies recorded: {replies}",
        f"Opt-outs recorded: {opt_outs}",
        f"Customers: {_line_value(dashboard, 'Customers')}",
        "",
        "ACTIVE PORTFOLIO",
        *active_strategies,
        "",
        f"Phase: {_line_value(state, 'Phase')}",
        f"Current bottleneck: {_emphasis_value(dashboard, 'Current bottleneck')}",
        f"Next highest-EV action: {_emphasis_value(dashboard, 'Next highest-EV action')}",
        "",
        "LATEST VERIFIED EVENTS",
        *latest_events,
        "",
        "REPOSITORY GATE",
        "Before every commit: regenerate this file, run the unit suite, run the mission validator, then push and verify the remote head.",
        "Commands: python tools/update_progress.py | python -m unittest discover -s tests -v | python tools/validate_mission.py",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    root = Path(__file__).resolve().parents[1]
    output = root / "progress.txt"
    output.write_text(build_progress(root), encoding="utf-8", newline="\n")
    print(f"Updated {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
